import { NavBar } from "@/components/NavBar";
import Sidebar from "@/components/Sidebar/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white container mx-auto h-screen`}
      >
        <div className="flex flex-col gap-4 h-screen py-2">
          <NavBar />

          <div className={`flex h-full max-w-[95%] min-w-[95%] mx-auto overflow-hidden gap-4 p-4`}>
            <Sidebar />
            <div className="bg-white h-full shadow-md flex-1 overflow-auto p-2">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
